### ISSUE TITLE
Foam on CI

### ISSUE THREAD

**Issue by Casyfill** [theowenyoung/foam-template-gatsby-theme-primer-wiki#2]
One thing I noticed with the gatsby-wiki theme, but probably applicable anywhere else, is that it is sometimes tempting to edit/work on the repository via online tools (especially given this wonderful "edit" button). Both Gitlab and Github now has built-in VS-code, so this is very convenient. However, those do not have FOAM installed (duh), which means there won't be any link ref generation. So it would probably be safe to have `foam-cli` run janitor anyway right before running `gatsby build`.

**Comment by theowenyoung** [comment]
yes, foam-cli docs say we should give it the workspace path, so it should be root. 

I have tested this, it works fine.
